#define	LINUX_RT_SIGF_HANDLER	0x100
#define	LINUX_RT_SIGF_SC	0x14
#define	LINUX_RT_SIGF_UC	0x8c
#define	LINUX_SC_EFLAGS	0x40
#define	LINUX_SC_GS	0x0
#define	LINUX_SIGF_HANDLER	0x2d0
#define	LINUX_SIGF_SC	0x4
